---
title: "Template for Project 1 Data Analysis Report (replace it with your own title)"
author: "Zeng Fung Liew (913802324), "
date: "February 2, 2021"
output:
  html_document:
    df_print: paged
    number_sections: yes
---
```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.pos = 'H')
```


# Introduction


# Background 


# Descriptive analysis 


# Inferential analysis 
```{r}
library(AER)
library(AER)
library(ggplot2)
library(gplots)
library(plotly)
library(tidyverse)
library(dplyr)
rm(list=ls())
data("Fatalities")
Fatalities$drinkage <-as.factor(floor(Fatalities$drinkage))
# apply(is.na(Fatalities), 2, which) 
data <- Fatalities  %>%mutate(fatal_r=(fatal/pop)*10000,afatal_r=(afatal/pop)*10000) %>% select(state,year,fatal_r,afatal_r,spirits,unemp,beertax,drinkage,dry,breath,jail,service,pop,fatal,nfatal)

library(plm)
plm_1 <- plm(fatal_r~unemp+jail+drinkage+beertax+spirits+dry+service+breath,data=data,index=c("state","year"),model="within")
coeftest(plm_1)
summary(plm_1)

plm_a <- plm(afatal_r~unemp+jail+drinkage+beertax+spirits+dry+service+breath,data=data,index=c("state","year"),model="within")
coeftest(plm_a)
summary(plm_a)
```


# Sensitivity analysis 


# Causal interpretation 


# Discussion 


# Acknowledgement {-}


# Reference {-}


# Session info {-}


```{r}
sessionInfo()
```
