---
title: "EDA_Liela"
author: "liela"
date: "2/5/2021"
output: html_document
---
```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.pos = 'H')
library(AER)
library(AER)
library(ggplot2)
library(gplots)
library(plotly)
library(tidyverse)
library(dplyr)
rm(list=ls())
data("Fatalities")
?Fatalities
Fatalities$drinkage <-as.factor(floor(Fatalities$drinkage))
apply(is.na(Fatalities), 2, which) 

data <- Fatalities  %>%mutate(fatal_r=(fatal/pop)*10000,nfatal_r=(nfatal/pop)*10000) %>% select(state,year,fatal_r,nfatal_r,spirits,unemp,beertax,drinkage,dry,breath,jail,service,pop,fatal,nfatal)
```
```{r visualization}
# mean (years)
mapping <- data %>%  select(state,year,nfatal_r,fatal_r,pop,fatal,nfatal) %>% mutate(state=toupper(state))
map <- mapping %>% group_by(state) %>% summarise(fatal=round(mean(fatal),2),fatal_r_mean=round(mean(fatal_r),2))
map$hover <- with(map, paste(state, '<br>', "fatal(mean)", fatal, "fatal ratio(mean)", fatal_r_mean))

# give state boundaries a white border
l <- list(color = toRGB("white"), width = 2)
# specify some map projection/options
g <- list(
  scope = 'usa',
  projection = list(type = 'albers usa'),
  showlakes = TRUE,
  lakecolor = toRGB('white')
)

fig <- plot_geo(map, locationmode = 'USA-states')
fig <- fig %>% add_trace(
    z = ~fatal_r_mean, text=~hover,locations = ~state,
    color = ~fatal_r_mean, colors = 'Purples'
  )
fig <- fig %>% colorbar(title = "Number of vehicle fatalities")
fig <- fig %>% layout(
    title = 'US Traffic Fatalities',
    geo = g,
  yaxis = list(type = "log")
  )
fig

# by year
gg <- ggplot(mapping, aes(pop,fatal_r, color = state)) +
  geom_point(aes(size = fatal_r, frame = year, ids = state)) +
  scale_x_log10()
ggplotly(gg)
```
```{r}
data %>% group_by(state) %>% summarise(mean=mean(dry),min=min(dry),max=max(dry)) %>% arrange(desc(mean))

data %>% group_by(state) %>% summarise(count=n())
```
```{r library}
library(AER)
library(plm)
library(stargazer)
```

```{r}
data %>% filter(state=="ar")
```

```{r fatal_r}
data %>% select(state,year,fatal_r) %>% group_by(state) %>% summarise(mean=mean(fatal_r),sd=sd(fatal_r),max=max(fatal_r),min=min(fatal_r),range=max(fatal_r)-min(fatal_r)) %>% arrange(desc(sd)) %>% plot_ly(x=~mean, type = "histogram")# %>% plot_ly(x=~state,y=~mean)
```
```{r spirits}
data %>% select(state,year,spirits) %>% group_by(state) %>% summarise(mean=mean(spirits),sd=sd(spirits),max=max(spirits),min=min(spirits),range=max(spirits)-min(spirits)) %>% arrange(desc(max)) %>% plot_ly(x=~mean, type = "histogram")# %>% plot_ly(x=~state,y=~mean)
```
```{r unemp}
data %>% select(state,year,unemp) %>% group_by(state) %>% summarise(mean=mean(unemp),sd=sd(unemp),max=max(unemp),min=min(unemp),range=max(unemp)-min(unemp)) %>% arrange(desc(sd)) %>% plot_ly(x=~mean, type = "histogram")# %>% plot_ly(x=~state,y=~mean)
```
```{r beertax}
data %>% select(state,year,beertax) %>% group_by(state) %>% summarise(mean=mean(beertax),sd=sd(beertax),max=max(beertax),min=min(beertax),range=max(beertax)-min(beertax)) %>% arrange(desc(mean)) %>% plot_ly(x=~mean, type = "histogram")# %>% plot_ly(x=~state,y=~mean)
```

```{r dry}
data %>% select(state,year,dry) %>% group_by(state) %>% summarise(mean=mean(dry),sd=sd(dry),max=max(dry),min=min(dry),range=max(dry)-min(dry)) %>% arrange(desc(mean)) %>% plot_ly(x=~range, type = "histogram")# %>% plot_ly(x=~state,y=~mean)
```
```{r breath}
year_breath <- data %>% select(state,year,breath) %>% pivot_wider(
  names_from = year,
  values_from = breath
) %>% as.data.frame()
```
```{r jail}
year_jail <- data %>% select(state,year,jail) %>% pivot_wider(
  names_from = year,
  values_from = jail
) %>% as.data.frame()
```

```{r}

library(readr)
library(fdapace)
library(tidyverse)
library(dplyr)
library(plyr)
library(fda)
library(lubridate)
library(ggplot2)
library(fdapace)
# original curves
smooth = data  %>% dplyr::select(state, year, fatal_r) %>% 
  ddply(.(state), mutate, years = 1:length(fatal_r), count_smooth = Lwls1D(bw = 2,
                                    kernel_type = 'epan', 
                                    xin = years, 
                                    yin = fatal_r, 
                                    xout = year))

local_linear <- smooth %>% dplyr::select(state,count_smooth,years) %>%  pivot_wider(
  names_from = state,
  values_from = count_smooth,
  values_fill = list(count_smooth = 0)
) %>% as.data.frame()%>% dplyr::select(-years)


# first-derivative
smooth_1 = data  %>% dplyr::select(state, year, fatal_r) %>% 
  ddply(.(state), mutate, years = 1:length(fatal_r), count_smooth = Lwls1D(bw = 2,
                                    kernel_type = 'epan', 
                                    xin = years, 
                                    yin = fatal_r, 
                                    xout = year,
                                    nder = 1))

local_linear_1 <- smooth_1 %>% dplyr::select(state,count_smooth,years) %>%  pivot_wider(
  names_from = state,
  values_from = count_smooth,
  values_fill = list(count_smooth = 0)
) %>% as.data.frame()%>% dplyr::select(-years)

par(mfrow=c(1,2))
matplot(1:7,local_linear, type = "l", lty = 1, xlab='years', ylab= 'fatal_ratio (y)',main = list("Smoothed original curves", cex = 0.8, font = 4))
matplot(1:7,local_linear_1, type = "l", lty = 1, xlab='years', ylab= 'Dy',main = list("First derivative original curves", cex = 0.8, font = 4))
```

```{r}
library(plm)
plm_1 <- plm(fatal_r~unemp+jail+drinkage+beertax+spirits+dry+service,data=data,index=c("state","year"),model="within")
coeftest(plm_1)
summary(plm_1)

```

